### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by ghost** [ChrisMacNaughton/cargo-cacher#11]
I get AccessDenied for every crate. I compared with cargo-download: Cargo-cache and cargo-download use the same URLs. cargo-download is working fine. I also read that the people running crates.io will never block mirroring tools, the are ok with mirroring people mirroring crates.io.

```bash
$ find -type f | wc -l; ag -l AccessDenied | wc -l
362
362
```

I use revision 8f07ed7. Is anybody else experiencing this?

**Comment by ChrisMacNaughton** [comment]
I started getting this today, a bit of digging led me to a slightly updated crate path that seems to work correctly, so I'm pushing an updated version to crates.io
