### ISSUE TITLE
After hour run of cacher zombie processes appears

### ISSUE THREAD

**Issue by bodynek** [ChrisMacNaughton/cargo-cacher#14]
I'm running cacher and after hour of run, zombie processes of git start to appear
```
  216 ?        Ssl    0:00 /opt/cargo-cacher/cargo-cacher -e http://cargo-kacer.gcx.com -u https://crates.io/api/v1/crates/
  426 ?        Z      0:00  \_ [git] <defunct>
  430 ?        Z      0:00  \_ [git] <defunct>
```

**Comment by jmlich** [comment]
There should be probably p.wait() somewhere at https://github.com/ChrisMacNaughton/cargo-cacher/blob/master/src/git.rs#L62

See https://doc.rust-lang.org/std/process/struct.Child.html

**Comment by ChrisMacNaughton** [comment]
Good spot @jmlich, thanks!
