### ISSUE TITLE
Config.json fails to commit/rebase

### ISSUE THREAD

**Issue by dellgreen** [ChrisMacNaughton/cargo-cacher#18]
Everytime I start cargo-cacher I end up with config.json being modified but not committed to the index repo, this then in turn results in crates not being written to the crates directory. I resolved the issue by manually committing config.json to the index repo.

Maybe on startup we should always check to make sure config.json is committed and if not commit it.

**Comment by dellgreen** [comment]
after running it for a few days via a systemd service, i can see that after and index update, the change made to config.json is now sitting on a no branch, which now prevents all future index updates. 

`diff --git a/config.json b/config.json
index b453be65ff9..13c648622df 100644
--- a/config.json
+++ b/config.json
@@ -1,4 +1,4 @@
 {
-  "dl": "https://crates.io/api/v1/crates",
-  "api": "https://crates.io"
+  "dl": "http://10.10.10.40:9200/api/v1/crates",
+  "api": "http://10.10.10.40:9200/"
 }
dell@loki:/media/zfs-data-pool/resources/cargo-cacher/index$ git branch
* (no branch)
  master
`

**Comment by dellgreen** [comment]
Looks like the rebase after a pull is failing with conflicts sometimes

**Comment by dellgreen** [comment]
Would it be better to not commit any changes to the repo, avoiding all chances of merge/rebase conflicts, and instead make the changes to config.json after a sync without committing. Then prior to every resync clean the git repo to remove any uncommitted changes? otherwise updating of index silent fails, resulting in uncached new crates.

Or does it need to be committed so clients can pull it down?

**Comment by ChrisMacNaughton** [comment]
It does have to be committed, as cargo actually clones the index before using the config to fetch crates. It is probably worth updating the config.yaml management to ensure that the commits don't conflict; possibly reset the latest commit before we update, but that sounds racy

**Comment by dellgreen** [comment]
thanks, good to know. :) will take a look at it when I have a spare moment

**Comment by ChrisMacNaughton** [comment]
I'll have a thought as well about ways to resolve it as well - maybe something like a copy, pull the, revert the commit on the copy, update the copy, and swap it back to the current version; should be race free, but wouldn't be super clean or fun to code up

**Comment by dellgreen** [comment]
ok sounds great, i wonder is theres a more git-ish way to achieve a similar atomic way to achieve what we require without all the ceremony. Can we mark config.json is some way to not be merged?  for example via .gitattributes
https://stackoverflow.com/questions/332528/is-it-possible-to-exclude-specific-commits-when-doing-a-git-merge/3970442#3970442

**Comment by dellgreen** [comment]
I have added a .git/info/attributes file to the index local repo on my server with "config.json merge=ours" in it to see how this works over time

**Comment by ChrisMacNaughton** [comment]
I'm excited to hear if it resolves the issues with the merges!

**Comment by dellgreen** [comment]
Ok, have found the problem. Its the commit which is failing not the rebase. The rebase compounds the problem as the previous commit failed and working tree is not clean.

I am running cargo-cacher via systemd and by default git is unable to find the git config for the root user, which is in turn then causing the rust commit command to fail silently. One way to  fix this is by 
 by adding the a git user to the .git/config file in the index repo.

The reason it was difficult to track down, is because in the rust git command stderr is being redirected to /dev/null resulting in no errors appearing in system logs/journalctl.

It may be an idea to do either or both:

1) As part of startup of cargo-cacher set a default user in .git/config, As the process is auto-committing anyway it possibly doesn't matter what the user.name and user.email is for the auto commit

2) remove redirecting of stderr to /dev/null in the rust command so that its much easier to diagnose problems with the commands. 

:)
